version: '3'

services:
  nginx:
    build:
      context: ./nginx
      args:
        - NGINX_IMAGE_VERSION=${NGINX_IMAGE_VERSION}
    container_name: "laravel-nginx"
    environment:
      TZ: ${TIME_ZONE}
    ports:
      - "${NGINX_HTTP_PORT}:80"
      - "${NGINX_HTTPS_PORT}:443"
    volumes:
      - ${NGINX_DEFAULT_CONF_PATH}:/etc/nginx/conf.d/default.conf
      - ${NGINX_LOG_PATH}:/var/log/nginx
      - ${NGINX_LOGROTATE_PATH}:/etc/logrotate.d/nginx
      - ${PROJECT_PATH}:/var/www/html
    depends_on:
      - db
  php:
    build:
      context: ./php
      args:
        - PHP_IMAGE_VERSION=${PHP_IMAGE_VERSION}
        - XDEBUG_VERSION=${XDEBUG_VERSION}
        - NODE_VERSION=${NODE_VERSION}
        - LARAVEL_VERSION=${LARAVEL_VERSION}
    container_name: "laravel-php"
    environment:
      TZ: ${TIME_ZONE}
      LARAVEL_VERSION: ${LARAVEL_VERSION}
      DATABASE: ${DATABASE}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      TESTING_DATABASE: ${TESTING_DATABASE}
    volumes:
      - ${PHP_INI_PATH}:/usr/local/etc/php/php.ini
      - ${XDEBUG_INI_PATH}:/usr/local/etc/php/conf.d/zz-xdebug.ini
      - ${PROJECT_PATH}:/var/www/html
    depends_on:
      - db
  db:
    build:
      context: ${DATABASE_BUILD_PATH}
      args:
        - DATABASE_IMAGE_VERSION=${DATABASE_IMAGE_VERSION}
    container_name: "laravel-database"
    restart: always
    environment:
      MYSQL_DATABASE: ${DATABASE}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASS}
      TESTING_DATABASE: ${TESTING_DATABASE}
      TZ: ${TIME_ZONE}
    volumes:
      - ${DATABASE_CONF}:/etc/mysql/conf.d
      - ${DATABASE_DATA}:/var/lib/mysql
      - ${DATABASE_INIT}:/docker-entrypoint-initdb.d
    ports:
      - "${DATABASE_PORT}:3306"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:${PHPMYADMIN_VERSION}
    container_name: "laravel-phpmyadmin"
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
      - PMA_USER=${DATABASE_USER}
      - PMA_PASSWORD=${DATABASE_PASSWORD}
    depends_on:
      - db
    ports:
      - ${PHPMYADMIN_PORT}:80
